---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - kubernetes-crd-definition-v1.yml
  - kubernetes-crd-rbac.yml
  - gateway.networking.k8s.io_gatewayclasses.yaml
  - gateway.networking.k8s.io_gateways.yaml
  - gateway.networking.k8s.io_httproutes.yaml
  - gateway.networking.k8s.io_tcproutes.yaml
  - gateway.networking.k8s.io_tlsroutes.yaml
  - kubernetes-gateway-rbac.yml
