---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - origin
  - traefik.pvc.yml
  - traefik.serviceAccount.yml
  - traefik.yml
configMapGenerator:
  - name: traefik-static-config
    files:
      - traefik.yml=data/traefik-static-config.yml
