---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: traefik-ingress-lb
  name: traefik
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      containers:
        - args:
            - --configfile=/etc/traefik/traefik.yml
          image: traefik:v2.10.3
          name: traefik-ingress-lb
          envFrom:
            - secretRef:
                # A secret with this name should be defined
                # in the user's cluster.
                name: traefik-static-config-secret
          volumeMounts:
            - name: traefik-data
              mountPath: /traefik-data
            - name: traefik-static-config
              mountPath: /etc/traefik
              subPath: traefik.yml
              readOnly: true
          ports:
            - containerPort: 80
              hostPort: 80
              name: web
            - containerPort: 443
              hostPort: 443
              name: websecure
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: traefik-data
          persistentVolumeClaim:
            claimName: traefik-data
        - name: traefik-static-config
          configMap:
            name: traefik-static-config
