---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
configMapGenerator:
  - name: traefik-static-config
    files:
      - traefik.yml: data/traefik-static-config.yml
