---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    - name: websecure
      port: 443
      protocol: TCP
      targetPort: 443
    - name: http3
      port: 443
      protocol: UDP
      targetPort: 443
  selector:
    k8s-app: traefik-ingress-lb
  type: LoadBalancer
